# -*- coding: utf-8 -*-
"""Clase.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fc7A3_UvbZCPxUuWYc0_HlSl5wOzHz3k

POO - Creacion de una clase
Clase persoma
Atributos


*   Nombre
*   Edad Metodos
*   Saludar()
"""

#Crear clase persona
class Persona:
  def __init__(self, nombre, edad):
    self.nombre = nombre
    self.edad = edad

  def saludar(self):
    print("Hola, mi nombre es", self.nombre, "y tengo", self.edad, "años")

#Llamar clase persona
persona1 = Persona("Juan", 25)
persona1.saludar()

persona2 = Persona("Maria", 30)
persona2.saludar()

persona3 = Persona("Pedro", 35)
persona3.saludar()

persona4 = Persona("Ana", 40)
persona4.saludar()

persona5 = Persona("Luis", 45)
persona5.saludar()